apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdeploy
  labels:
    app: webapp    
spec:
  selector:
    matchLabels:      
      app: webapp
      env: production    
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app: webapp   
        env: production    
    spec:
      containers:
        - name: webcon     
          image: image_name
          volumeMounts:
            - name: myvol1      
              mountPath: host_path
            - name: myvol2
              mountPath: log_path    
          ports:
            - name: webcon
              containerPort: 80      

      volumes:
        - name: myvol1      
          persistentVolumeClaim:
            claimName: pvc_name1
        - name: myvol2
          persistentVolumeClaim:
            claimName: pvc_name2      


  


